require:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - '**/._*'
    - 'bin/*'
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
